# Generated by Django 5.2.3 on 2025-06-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subscriptionplan_delete_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price_description',
        ),
    ]
