"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables as early as possible.
load_dotenv(BASE_DIR / ".env")


def _convert_bool(value: str, default: bool = False) -> bool:
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "t", "yes", "y", "on"}


# Deployment toggles
DEMO_MODE = _convert_bool(os.getenv("DEMO_MODE", "true"), default=True)
ENABLE_AUTH = _convert_bool(os.getenv("ENABLE_AUTH", "false")) and not DEMO_MODE
ENABLE_REAL_PAYMENTS = _convert_bool(os.getenv("ENABLE_REAL_PAYMENTS", "false")) and not DEMO_MODE
ENABLE_REAL_CHAT = _convert_bool(os.getenv("ENABLE_REAL_CHAT", "false")) and not DEMO_MODE

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "demo-secret-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _convert_bool(os.getenv("DEBUG", "true"), default=True)

ALLOWED_HOSTS = [host.strip() for host in os.getenv("ALLOWED_HOSTS", "*").split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    "whitenoise.runserver_nostatic",
    "app",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.demo_flags",
            ],
        },
    },
]
LOGIN_URL = "/login/"

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / os.getenv("SQLITE_NAME", "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email
if DEMO_MODE:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    EMAIL_HOST_USER = "demo@example.com"
else:
    EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = _convert_bool(os.getenv("EMAIL_USE_TLS", "true"), default=True)
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Stripe / Payment configuration
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_PUBLIC_KEY = os.getenv("STRIPE_PUBLIC_KEY", "")
STRIPE_PRICE_IDS = {
    "monthly": os.getenv("STRIPE_PRICE_ID_MONTHLY", ""),
    "quarterly": os.getenv("STRIPE_PRICE_ID_QUARTERLY", ""),
    "yearly": os.getenv("STRIPE_PRICE_ID_YEARLY", ""),
}
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

# Demo pricing text for display only (no real payments)
DEMO_PLAN_PRICING = {
    "monthly": os.getenv("DEMO_PRICE_MONTHLY", "€9 / month"),
    "quarterly": os.getenv("DEMO_PRICE_QUARTERLY", "€24 / 3 months"),
    "yearly": os.getenv("DEMO_PRICE_YEARLY", "€79 / year"),
}

# Demo chat fallback content
DEMO_CHAT_RESPONSES = [
    item.strip()
    for item in os.getenv(
        "DEMO_CHAT_RESPONSES",
        "Remember: consistency beats intensity. Choose one action you can finish before the day ends.|"
        "Audit your last 24 hours. What helped you move forward? What held you back?|"
        "Take a 5-minute reset. Breathe, re-focus, then attack the hardest task on your list.|"
        "Write down the one standard you refuse to compromise on this week.",
    ).split("|")
    if item.strip()
]


# CSRF / cookies for deployments behind proxies
if "CSRF_TRUSTED_ORIGINS" in os.environ:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if origin.strip()]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
